// Generated by BUCKLESCRIPT VERSION 1.9.2, PLEASE EDIT WITH CARE
'use strict';


var name = "Wiro Sableng";

console.log(name);

var street = "Jl. Utama Raya";

var city = "Kota Tangerang";

var address = "Jl. Utama Raya, Kota Tangerang";

console.log(address);

var totalPrice = 35000;

console.log("Total Harga: " + (String(totalPrice) + ""));

var title = "Saur Sepuh";

var priceA = 10000;

var priceB = 25000;

exports.title      = title;
exports.name       = name;
exports.street     = street;
exports.city       = city;
exports.address    = address;
exports.priceA     = priceA;
exports.priceB     = priceB;
exports.totalPrice = totalPrice;
/*  Not a pure module */
